# coverage.yml  Generate and upload Go code coverage report to Codecov.
# https://github.com/onflow/atree/blob/main/.github/workflows/coverage.yml

name: coverage

# Remove permissions from top level and grant in jobs.
permissions: {}

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          check-latest: true

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build project
        run: go build ./...

      - name: Generate coverage report
        run: go test -timeout 180m -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@5a605bd92782ce0810fa3b8acc235c921b497052 # v5.2.0
        with:
            files: ./coverage.txt
            fail_ci_if_error: false # we can set this to true after "Could not find a repository" upload error is fixed
            verbose: true # optional (default = false)
