# coverage.yml  Generate and upload Go code coverage report to Codecov.
# https://github.com/onflow/atree/blob/main/.github/workflows/coverage.yml

name: coverage

# Remove permissions from top level and grant in jobs.
permissions: {}

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          check-latest: true

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build project
        run: go build ./...

      - name: Generate coverage report
        run: go test -timeout 60m -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4.0.1  
        with:
            files: ./coverage.txt
            fail_ci_if_error: false # we can set this to true after "Could not find a repository" upload error is fixed
            verbose: true # optional (default = false)
