# coverage.yml  Generate and upload Go code coverage report to Codecov.
# 2021-11-26    Created github.com/onflow/atree/.github/workflows/coverage.yml

name: coverage
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # allow GitHub to use latest v2.x of checkout
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v2  # allow GitHub to use latest v2.x of setup-go
        with:
          go-version: '1.17.x'

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build project
        run: go build ./...

      - name: Generate coverage report
        run: go test -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2.1.0  # use v2.1.0, we can manually update uploader version if needed
        with:
            files: ./coverage.txt
            fail_ci_if_error: true # optional (default = false)
            verbose: true # optional (default = false)
